"""empty message

Revision ID: 242199ac47d0
Revises: None
Create Date: 2019-10-24 00:16:42.549554

"""

# revision identifiers, used by Alembic.
revision = '242199ac47d0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hmt', sa.String(length=20), nullable=False),
    sa.Column('tmp', sa.String(length=20), nullable=False),
    sa.Column('ppm', sa.String(length=20), nullable=False),
    sa.Column('lx', sa.String(length=20), nullable=False),
    sa.Column('ld', sa.String(length=20), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iots')
    # ### end Alembic commands ###
