API_URL = 'http://iotplatform.yfgeek.com/api/v1/iot'
BROADCAST_INTERVAL = 18
POST_INTERVAL_TIME = 60
BITCOIN_IOT_SENDER_KEY = 'cNyYBxvt1BvAq3svjTZWg4LN828bzPimax2C7pipPjbUzgWYDXdp'
BITCOIN_IOT_RECEIVER = 'myfM3Pph3NjNeihjEXFPvGdhpfiQKYv372'
BITCOIN_TRANSFER_AMOUNT = 0.000001
LOCAL_FOLDER_DIR = "/home/pi/Projects/sensors/data/"

IS_POST_TO_SERVER = 1
IS_SAVE_TO_LOCAL = 1
IS_BROADCAST_TO_BLOCKCHAIN = 1